global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'fastapi:8502'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rain_.*|http_requests_total|http_request_duration_seconds.*|http_request_duration_highr_seconds.*'
        action: keep
