apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: rain-prediction
type: Opaque
stringData:
  AIRFLOW_DB_USER: airflow
  AIRFLOW_DB_PASSWORD: rain-airflow-db-change-me
  AIRFLOW_DB_NAME: airflow
  AIRFLOW_ADMIN_USER: admin
  AIRFLOW_ADMIN_PASSWORD: airflow
  AIRFLOW_ADMIN_EMAIL: admin@example.com
  AIRFLOW_REDIS_PASSWORD: rain-airflow-redis-change-me
  AIRFLOW__CORE__FERNET_KEY: XUam0SP0UKSzZC-bUAC-6Za66AHLa7s80qG71BRhn48=
  AIRFLOW__WEBSERVER__SECRET_KEY: UrLiGM7e4QPmPg_x5bn8Bf-SOXYNWvR0ckgiA0rHwphy4g8iy64DzW5AgpG8Egjv
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:rain-airflow-db-change-me@airflow-postgres:5432/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:rain-airflow-db-change-me@airflow-postgres:5432/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://:rain-airflow-redis-change-me@airflow-redis:6379/0
