apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-project
  namespace: rain-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: rain-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
