apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: rain-prediction
data:
  AIRFLOW_PROJECT_DIR: /opt/airflow/project
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__PARALLELISM: "32"
  AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "16"
  AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "1"
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "1"
  AIRFLOW__WEBSERVER__WORKERS: "2"
  AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_SERVER_PORT: "8974"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
  AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
  MLOPS_E2E_SCHEDULE: ""
