apiVersion: v1
kind: Service
metadata:
  name: rain-prediction-api
  namespace: rain-prediction
spec:
  type: ClusterIP
  selector:
    app: rain-prediction-api
  ports:
    - name: http
      port: 8502
      targetPort: 8502
